embed_images: datauri
compress_assets: on
template_function: _.template
gzip_assets: on

javascripts:
    viewer:
        - public/js/DV/vendor/jquery-1.7.1.min.js 
        - public/js/DV/vendor/jquery-ui-1.8.1.custom.min.js                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
        - public/js/DV/vendor/jquery.acceptInput.js                                                                                                                                                                                    
        - public/js/DV/vendor/jquery.placeholder.js                                                                                                                                                                                    
        - public/js/DV/lib/initializer.js                                                                                                                                                                                              
        - public/js/DV/lib/*.js                                                                                                                                                                                                        
        - public/js/DV/schema/*.js                                                                                                                                                                                                     
        - public/js/DV/elements/*.js                                                                                                                                                                                                   
        - public/js/DV/models/*.js                                                                                                                                                                                                     
        - public/js/DV/events/events.js                                                                                                                                                                                                
        - public/js/DV/events/View*.js                                                                                                                                                                                                 
        - public/js/DV/events/*.js                                                                                                                                                                                                     
        - public/js/DV/helpers/helpers.js                                                         
        - public/js/DV/helpers/*.js                                                                                                                                                                                                    
        - public/js/DV/states/*.js                                                                                                                                                                                                     
        - public/js/DV/controllers/*.js

    templates:                                                                                                                                                                                                                                
        - public/js/DV/views/*.jst

    bootstraps:
        - public/bootstrap/js/bootstrap-modal.js
        - public/bootstrap/js/bootstrap-transition.js
        - public/bootstrap/js/bootstrap-tooltip.js
        - public/bootstrap/js/bootstrap-popover.js

    mainpipe:
        - public/js/libs/modernizr.js
        - public/js/libs/underscore.js
        - public/js/libs/respond.min.js
        - public/js/plugins.js
        - public/js/app.js

    index:
        - public/js/modules/ytube.js
        - public/js/modules/front.js
        - public/js/libs/jquery.marquee.js
        - public/js/modules/nytimes.js

    DV: 
        - public/js/libs/jquery-ui-1.8.18.custom.min.js
        - public/js/modules/bootstraps.js
        - public/js/modules/jloupe.js
        - public/js/modules/DV_load.js
        - public/js/modules/pubsub.js
        - public/js/modules/magpie.js 

    results:
        - public/js/modules/bootstraps.js
        - public/js/modules/results.js
        - public/js/libs/jquery.marquee.js
        - public/js/modules/nytimes.js

    latest:
        - public/js/modules/latest.js

    analytics:
        - public/js/analytics.js


stylesheets:
    results:
        - public/css/bootstrap_ext.css
        - public/css/reset.css
        - public/css/text.css
        - public/css/base.css
        - public/css/results.css

    latest:
        - public/css/reset.css
        - public/css/text.css
        - public/css/base.css

    boot:
        - public/css/bootstrap_ext.css
        - public/css/reset.css
        - public/css/text.css
        - public/css/base.css
        - public/css/other.css

    viewer:                                                                                                                                                                                                                                   
        - public/css/DV/components/reset.css                                                                                                                                                                                            
        - public/css/DV/components/structure.css                                                                                                                                                                                        
        - public/css/DV/components/ui.css                                                                                                                                                                                               
        - public/css/DV/components/*.css                                                                                                                                                                                                
        - public/css/DV/themes/plain.css