defaults: &defaults  
    identity_map_enabled: true
    use_utc: true
    raise_not_found_error: false

development:  
    <<: *defaults
    port: 27017
    host: localhost
    database: dev_project

test:  
    <<: *defaults
    port: 27017
    host: localhost
    database: dev_project

production:  
    <<: *defaults
    uri: <%= ENV['MONGOHQ_URL'] %>