defaults: &defaults  
 name: nypl_labs_project
 identity_map_enabled: true

development:  
 <<: *defaults
 port: 27017
 host: localhost
 database: dev_project

test:  
 <<: *defaults

production:  
 <<: *defaults
 uri: <%= ENV['MONGOHQ_URL'] %>